<a href="https://colab.research.google.com/github/oerv13/Ibero/blob/main/Trabajo_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [16]:
from google.colab import files
uploaded = files.upload()

Saving deportistas_participantes_en_cada_competicion_de_juegos_olimpicos_de_verano.csv to deportistas_participantes_en_cada_competicion_de_juegos_olimpicos_de_verano.csv

In [18]:
url = 'deportistas_participantes_en_cada_competicion_de_juegos_olimpicos_de_verano.csv'
df = pd.read_csv(url)
df

,"Año;""Periodo"";""Parámetro"";""Nota: Berlín 1916","Tokio 1940 y Londres 1944 se suspendieron por las guerras mundiales"""
0,"2024;""Año"";""Amberes 1920"";""2.626""",NaN
1,"2024;""Año"";""Ámsterdam 1928"";""2.883""",NaN
2,"2024;""Año"";""Atenas 1896"";""241""",NaN
3,"2024;""Año"";""Atenas 2004"";""10.625""",NaN
4,"2024;""Año"";""Atlanta 1996"";""10.318""",NaN
5,"2024;""Año"";""Barcelona 1992"";""9.356""",NaN
6,"2024;""Año"";""Berlín 1916"";""0""",NaN
7,"2024;""Año"";""Berlín 1936"";""3.963""",NaN
8,"2024;""Año"";""Estocolmo 1912"";""2.587""",NaN
9,"2024;""Año"";""Helsinki 1952"";""4.955""",NaN
10,"2024;""Año"";""Londres 1908"";""2.008""",NaN
11,"2024;""Año"";""Londres 1944"";""0""",NaN
12,"2024;""Año"";""Londres 1948"";""4.104""",NaN
13,"2024;""Año"";""Londres 2012"";""10.500""",NaN
14,"2024;""Año"";""Los Ángeles 1932"";""1.332""",NaN
15,"2024;""Año"";""Los Ángeles 1984"";""6.829""",NaN
16,"2024;""Año"";""Melbourne 1956"";""3.314""",NaN
17,"2024;""Año"";""México City 1968"";""5.516""",NaN
18,"2024;""Año"";""Montreal 1976"";""6.084""",NaN
19,"2024;""Año"";""Moscow 1980"";""5.179""",NaN
20,"2024;""Año"";""Munich 1972"";""7.134""",NaN
21,"2024;""Año"";""París 1900"";""997""",NaN
22,"2024;""Año"";""París 1924"";""3.089""",NaN
23,"2024;""Año"";""París 2024"";""11.326""",NaN
24,"2024;""Año"";""Pekín 2008"";""10.942""",NaN
25,"2024;""Año"";""Río 2016"";""11.238""",NaN
26,"2024;""Año"";""Roma 1960"";""5.338""",NaN
27,"2024;""Año"";""San Luis 1904"";""691""",NaN
28,"2024;""Año"";""Seúl 1988"";""8.391""",NaN
29,"2024;""Año"";""Sidney 2000"";""10.651""",NaN
30,"2024;""Año"";""Tokio 1940"";""0""",NaN
31,"2024;""Año"";""Tokio 1964"";""5.151""",NaN
32,"2024;""Año"";""Tokio 2020"";""11.025""",NaN
33,;;,NaN
34,;;,NaN
35,"Métrica:""Nota: Berlín 1916",Tokio 1940 y Londres 1944 se suspendieron por...
36,"Fuente:""Olympian Database""",NaN
37,"Clasificación:""""",NaN
38,"Unidad:""Deportistas""",NaN
39,"Escala:""Unidades""",NaN
40,"EscalaFactorPotencia10:""0""",NaN
41,"SonDatosNumericos:""True""",NaN
42,;;,NaN
43,;;,NaN
44,"Url:""https://www.epdata.es/deportistas-partici...",NaN
45,"Titulo:""Deportistas participantes en cada comp...",NaN
46,"Subtitulo:""""",NaN

In [71]:
url = 'deportistas_participantes_en_cada_competicion_de_juegos_olimpicos_de_verano.csv'
df = pd.read_csv(url, encoding= 'latin-1', sep = ';')
df

,"ï»¿""AÃ±o""",Periodo,ParÃ¡metro,"Nota: BerlÃ­n 1916, Tokio 1940 y Londres 1944 se suspendieron por las guerras mundiales"
0,2024,AÃ±o,Amberes 1920,2.626
1,2024,AÃ±o,Ãmsterdam 1928,2.883
2,2024,AÃ±o,Atenas 1896,241.000
3,2024,AÃ±o,Atenas 2004,10.625
4,2024,AÃ±o,Atlanta 1996,10.318
5,2024,AÃ±o,Barcelona 1992,9.356
6,2024,AÃ±o,BerlÃ­n 1916,0.000
7,2024,AÃ±o,BerlÃ­n 1936,3.963
8,2024,AÃ±o,Estocolmo 1912,2.587
9,2024,AÃ±o,Helsinki 1952,4.955
10,2024,AÃ±o,Londres 1908,2.008
11,2024,AÃ±o,Londres 1944,0.000
12,2024,AÃ±o,Londres 1948,4.104
13,2024,AÃ±o,Londres 2012,10.500
14,2024,AÃ±o,Los Ãngeles 1932,1.332
15,2024,AÃ±o,Los Ãngeles 1984,6.829
16,2024,AÃ±o,Melbourne 1956,3.314
17,2024,AÃ±o,MÃ©xico City 1968,5.516
18,2024,AÃ±o,Montreal 1976,6.084
19,2024,AÃ±o,Moscow 1980,5.179
20,2024,AÃ±o,Munich 1972,7.134
21,2024,AÃ±o,ParÃ­s 1900,997.000
22,2024,AÃ±o,ParÃ­s 1924,3.089
23,2024,AÃ±o,ParÃ­s 2024,11.326
24,2024,AÃ±o,PekÃ­n 2008,10.942
25,2024,AÃ±o,RÃ­o 2016,11.238
26,2024,AÃ±o,Roma 1960,5.338
27,2024,AÃ±o,San Luis 1904,691.000
28,2024,AÃ±o,SeÃºl 1988,8.391
29,2024,AÃ±o,Sidney 2000,10.651
30,2024,AÃ±o,Tokio 1940,0.000
31,2024,AÃ±o,Tokio 1964,5.151
32,2024,AÃ±o,Tokio 2020,11.025
33,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN
35,"MÃ©trica:""Nota: BerlÃ­n 1916, Tokio 1940 y Lon...",NaN,NaN,NaN
36,"Fuente:""Olympian Database""",NaN,NaN,NaN
37,"ClasificaciÃ³n:""""",NaN,NaN,NaN
38,"Unidad:""Deportistas""",NaN,NaN,NaN
39,"Escala:""Unidades""",NaN,NaN,NaN
40,"EscalaFactorPotencia10:""0""",NaN,NaN,NaN
41,"SonDatosNumericos:""True""",NaN,NaN,NaN
42,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN
44,"Url:""https://www.epdata.es/deportistas-partici...",NaN,NaN,NaN
45,"Titulo:""Deportistas participantes en cada comp...",NaN,NaN,NaN
46,"Subtitulo:""""",NaN,NaN,NaN

In [22]:
# Atributos de exploración de los df
df.shape

(47, 4)

In [23]:
df.columns

Index(['ï»¿"AÃ±o"', 'Periodo', 'ParÃ¡metro',
       'Nota: BerlÃ­n 1916, Tokio 1940 y Londres 1944 se suspendieron por las guerras mundiales'],
      dtype='object')

In [72]:
# Modifiquemos los nombres de las variables
name = ['Year','Period','Parameter','Players']

df.columns = name
df.columns

Index(['Year', 'Period', 'Parameter', 'Players'], dtype='object')

In [51]:
# Métodos generalesde exploración

# df.head(3)
# df.tail(n = 10)
df.sample(n = 3)

,Year,Period,Parameter,Players
45,"Titulo:""Deportistas participantes en cada comp...",NaN,NaN,NaN
35,"MÃ©trica:""Nota: BerlÃ­n 1916, Tokio 1940 y Lon...",NaN,NaN,NaN
20,2024,AÃ±o,Munich 1972,7.134

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Year       43 non-null     object
 1   Period     33 non-null     object
 2   Parameter  33 non-null     object
 3   Players    33 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.6+ KB

In [101]:
df.isna().sum()

Year          4
Period       14
Parameter    14
Players      14
dtype: int64

In [114]:
## Limpeza de datos

df.replace('Ã±','nn',regex = True, inplace= True)
df.replace('Ã','i',regex = True, inplace= True)
df.replace('i','A',regex = True, inplace= True)
df.replace('i©','e',regex = True, inplace= True)
df.replace('iº','u',regex = True, inplace= True)
#df.head()
df.sample(5)

                          Year Period         Parameter  Players
21                        2024   Anno       Pari­s 1900  997.000
1                         2024   Anno    Amsterdam 1928    2.883
40  EscalaFactorPotencia10:"0"    NaN               NaN      NaN
41    SonDatosNumericos:"True"    NaN               NaN      NaN
15                        2024   Anno  Los Angeles 1984    6.829